# Generated by Django 5.2.17 on 2026-09-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_documentchunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('top_k', models.PositiveIntegerField(default=5)),
                ('min_similarity', models.FloatField(default=0.2)),
                ('document_ids', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question Answer',
                'verbose_name_plural': 'Question Answers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id_snapshot', models.PositiveBigIntegerField()),
                ('document_title', models.CharField(max_length=255)),
                ('chunk_index', models.PositiveIntegerField()),
                ('similarity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_answer_sources', to='documents.documentchunk')),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='qa.questionanswer')),
            ],
            options={
                'verbose_name': 'Question Answer Source',
                'verbose_name_plural': 'Question Answer Sources',
                'ordering': ['question_answer_id', '-similarity', 'id'],
            },
        ),
    ]
