# Generated by Django 5.2.17 on 2026-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
